service: serverless-stepf-store-checkout

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  lambdaHashingVersion: 20201221

plugins:
  - serverless-step-functions
  - serverless-export-env
  - serverless-iam-roles-per-function

custom:
  stage: ${opt:stage, self:provider.stage}
  export-env:
    overwrite: true

functions:
  checkInventory: ${file(./serverless/lambda.yml):checkInventory}
  calculateTotal: ${file(./serverless/lambda.yml):calculateTotal}
  redeemPoints: ${file(./serverless/lambda.yml):redeemPoints}
  billCustomer: ${file(./serverless/lambda.yml):billCustomer}
  restoreRedeemPoints: ${file(./serverless/lambda.yml):restoreRedeemPoints}
  sqsWorker: ${file(./serverless/lambda.yml):sqsWorker}
  restoreQuantity: ${file(./serverless/lambda.yml):restoreQuantity}

resources:
  Resources:
    BookTable: ${file(./serverless/dynamodb.yml):BookTable}
    UserTable: ${file(./serverless/dynamodb.yml):UserTable}
    OrdersQueue: ${file(./serverless/sqs.yml):OrdersQueue}
    OrdersTopic: ${file(./serverless/sns.yml):OrdersTopic}
  Outputs:
    BookTableName:
      Value: !Ref BookTable
    UserTableName:
      Value: !Ref UserTable
    OrdersQueueUrl:
      Value: !Ref OrdersQueue
    StoreCheckoutStateMachineArn:
      Value:
        Ref: StoreCheckoutFlow

stepFunctions: ${file(./serverless/stepFunctionsStateMachines.yml)}
