service: serverless-stepf-store-checkout

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  lambdaHashingVersion: 20201221

plugins:
  - serverless-step-functions

functions:
  hello:
    handler: handler.hello
